import '../styles/globals.css'
import Head from 'next/head'
import { styled } from '@mui/styles'

const Container = styled('div')(() => ({
  minHeight: '100vh',
  width: '100%',
}))

function MyApp({ Component, pageProps }) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      />
      <Component {...pageProps} />
    </Container>
  )
}

export default MyApp
